# Generated by Django 3.0.8 on 2020-08-07 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='datefinish',
        ),
        migrations.AddField(
            model_name='event',
            name='datestart',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='raceresult',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='stage0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='stages',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='startlist',
            field=models.BooleanField(default=True),
        ),
    ]
